services:
  # The PostgreSQL Database Service
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Note: We don't expose the port to the host, as it's only needed by the server internally.

  # The Node.js Backend API Service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - db

    

  # The React Frontend Service (served by Nginx)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80" # Map host port 80 to the container's port 80
    depends_on:
      - server # The client will wait for the server to be ready.

# Define named volumes for data persistence
volumes:
  postgres_data:
  uploads_data: