version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - urbex-net

  # This is now our single application service
  app:
    image: ghcr.io/your-github-username/urbex-map:latest
    restart: always
    env_file: ./.env
    ports:
      # Expose the application on port 8080
      - "8080:3001"
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - db
    networks:
      - urbex-net

volumes:
  postgres_data:
  uploads_data:

networks:
  urbex-net:
    driver: bridge