# This file is for LOCAL DEVELOPMENT ONLY.
# It runs the database and mounts the local source code into the app container
# to enable hot-reloading.

services:
  db:
    image: postgres:15
    container_name: urbex_db_dev
    restart: always
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - urbex-dev-net

  app-dev:
    # We build from the root Dockerfile, but will override the command
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urbex_app_dev
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    networks:
      - urbex-dev-net
    depends_on:
      - db

volumes:
  postgres_dev_data:
  uploads_dev_data:

networks:
  urbex-dev-net:
    driver: bridge